package main

import (
	"fmt"
)

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

// Calls the given function with each element in the Fibonacci sequence. Return false to stop iteration.
func fibonacci(cont func(int) bool) {
	var x, y = 1, 1
	if cont(0) {
		for cont(x) {
			x, y = y, x+y
		}
	}
}

func run002() {
	fmt.Print("002: ")

	var sum int
	fibonacci(func(x int) bool {
		if x%2 == 0 {
			sum += x
		}
		return x < 4000000
	})

	fmt.Printf("The sum of all the even Fibonacci numbers below four million is %d.", sum)
}
